FROM node:7.10.0-alpine

ARG STRAVA_CLIENT_SECRET

WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/

RUN npm config set registry http://registry.npmjs.org/ && \
    npm install nodemon -g && yarn upgrade && npm install

COPY . /usr/src/app

EXPOSE 3000

CMD [ "yarn", "webserver" ]
